#:kivy 1.9.1
#:set blue [.1,.45,.55]
#:set blue_a [.1,.45,.55,1]
#:set white [1,1,1,1]
#:set black [1,1,1,0]
#:set grey [0,0,0,.2]
#:include force new_btn.kv
#:include force new_lbl.kv
#:include force cell.kv
#:include force header.kv
#:include body.kv

<Block@BoxLayout>:		
	orientation: 'vertical'
	padding:6
	canvas:
		Color:
			rgba: white
		Rectangle:
			size: self.size
			pos: self.pos
			
<GreyTxt@Label>:
	size_hint_x:.6
	size:self.texture_size
	text_size:self.width,self.height
	valign:'top'
	font_size:25
	padding:0,15
	color: [.3,.3,.3,.6]

# 1) цвета занести в переменные	
# 2) разнести классы по модулям

<Test>:
	orientation: 'vertical'
	Header:
		Label:
			size_hint_x:None
			size:self.texture_size
			font_size:45
			text:'Меню'
	Block:
		Block:
			Cell:
				GridLayout:
					spacing:6
					rows:2
					cols:2
					NewButton:
						text:'Гайды для новичков'
					NewButton:
						text:'Статьи для продвинутых'
					NewButton:
						text:'Документация'
					NewButton:
						text:'Вопросы и ответы'
			Body:
				Block:
					NewLabel:
						text:'Новый пост'
					GreyTxt:
						text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed laoreet dignissim scelerisque. Proin tempus erat.'
					NewButton:
						padding:3,2
						size_hint:None,None
						size:self.texture_size
						text:'Читать'
	
	
